weights: ./runs/train/yolov7_full_vertical_flip_1600_400/weights/last.pt
cfg: ''
data: data/particleFull.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 400
batch_size: 5
img_size:
- 1600
- 1600
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: 1
workers: 8
project: runs/train
entity: null
name: yolov7_full_vertical_flip_1600_400
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 4
global_rank: 1
save_dir: runs/train/yolov7_full_vertical_flip_1600_400
total_batch_size: 20
